version: '3'
services:
  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes: 
      - db-data:/var/lib/mysql
volumes:
  db-data:

